### ISSUE TITLE
Alert popup every time

### ISSUE THREAD

**Issue by mehulparmar4ever** [crashoverride777/SwiftyRate#3]
Hello,

**I have added below code, But still alert popup in every time app launch.
I am unable to use this condition: afterAppLaunches: 50**

#Need Help

```
func giveRatingToApp() {
        let ratingsRequest = SwiftyRate.Request(
            afterAppLaunches: 50,
            customAlertTitle: "Rate My App",
            customAlertMessage: "RATE_ALERT_MSG".localized,
            customAlertActionCancel: "Remind me later"
            
        )
        SwiftyRate.requestReview(ratingsRequest, from: self)
    }
```

**Comment by crashoverride777** [comment]
Hey,

Thank you for your comment. I presume you are running an iOS version higher than iOS 10.3? In that case it will show the default apple ratings prompt instead of the custom one. Its the one you can select the stars from 1-5. This alert is managed by apple and will show every time you are in debug mode. Once you release your app to the App Store, it will not display every time.

https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview

The 50 app launches you have set only applies to the custom alert, which is only used on iOS versions below iOS 10.3

Hope this helps.

**Comment by mehulparmar4ever** [comment]
Hi @crashoverride777 ,

Thanks for your quick reply. Sorry If I hurt you in my below comment. If you want then I can also delete it later. I am really sorry for that again. :-(

May I know why you added below parameters.

            afterAppLaunches: 50,
            customAlertTitle: "Rate My App",
            customAlertMessage: "RATE_ALERT_MSG".localized,
            customAlertActionCancel: "Remind me later"

@crashoverride777 , You should inform in your readme file in header that: 

### > **For ABOVE IOS 11 users, This is not for you. DO NOT USE THIS.**
> Please don't waste your time using ,my repo for the users which are using iOS 11 or later
> 


just one line is enough, right!! 
;-)

```
SKStoreReviewController.requestReview()
```

**Comment by crashoverride777** [comment]
Hey

You are correct, that one line is enough if you are targeting iOS 10.3 and above. I will update the readme to make this clearer. 

Thanks again
